version: '3.7'
services:
  mysql:
    image: mysql:8.0.26
    platform: linux/x86_64
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:15.3
    platform: linux/x86_64
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass